const path=require("path");
require("dotenv").config({path:path.resolve(__dirname,"../.env")});
const express=require("express");const cors=require("cors");
const logger=require("./core/logger");
const app=express();
app.use(cors());
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:false}));
app.use("/previews",express.static(path.join(__dirname,"previews")));
require("./routes")(app);
app.use((err,req,res,next)=>{logger.error("GLOBAL ERROR:",err);res.status(500).json({ok:false,error:"Erro interno no servidor."});});
const PORT=process.env.PORT||4455;
app.listen(PORT,()=>logger.info(`YUNO FIXED running on ${PORT}`));